version: "2"

services:
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false
    restart: always

  samba:
    image: dperson/samba:rpi
    restart: unless-stopped
    command: >
      -p
      -w "G"
      -s "media;/media;yes;no;yes;all;none;;media"
      -s "torrents;/torrents;yes;no;yes;all;none;;torrents"
    environment:
      - USERID=1000
      - GROUPID=1000
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/torrents

  jellyfin:
    image: linuxserver/jellyfin:version-10.6.4-1
    ports:
      - 8096:8096
    volumes:
      - ${STORAGE}/Jellyfin:/config
      - ${MEDIA}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    restart: unless-stopped

  transmission:
    image : linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - TZ=America/Argentina/Buenos_Aires
      - USER=admin
      - PASS=supersecret
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.1.82
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - FG_LOG_LEVEL=error
    volumes:
      - ./flexget:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    restart: unless-stopped
    links:
      - transmission
