version: "2"

services:
  jellyfin:
    image: linuxserver/jellyfin:arm32v7-20200404-ls55
    expose:
      - 8096
    hostname: raspberrypi
    volumes:
      - ${STORAGE}/Jellyfin:/config
      - ${MEDIA}:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    restart: unless-stopped
    network_mode: "host"

  transmission:
    image : jaymoulin/transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    build: flexget-arm
    volumes:
      - ./flexget:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=superSecret421
    restart: unless-stopped
    links:
      - transmission
